// The stylable parts of core's widgets, read out of the components that draw
// them. A part is a `data-widget-part` token on an element core-catalog renders
// (`messages.message-avatar`, `stat-slot.bar`, the generic `card`), and the
// components are the only place one is declared, so the guide's list is
// generated from them rather than written beside them. `gen-widget-parts.ts`
// writes the list into guides/widgets.md; `sdk-tests/widgetParts.test.ts` holds
// the committed guide to this output.
import { readdirSync, readFileSync } from 'node:fs'
import path from 'node:path'

/** The guide the list lives in, relative to the repo root. */
export const WIDGET_PARTS_GUIDE = 'guides/widgets.md'
const BEGIN = '<!-- widget-parts:begin (generated by scripts/gen-widget-parts.ts) -->'
const END = '<!-- widget-parts:end -->'

const COMPONENTS = path.join(import.meta.dirname, '..', 'core-catalog', 'components')

function svelteFiles(dir: string): string[] {
	return readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
		e.isDirectory()
			? svelteFiles(path.join(dir, e.name))
			: e.name.endsWith('.svelte')
				? [path.join(dir, e.name)]
				: [],
	)
}

/** Every part token core's components carry: owner → part names, and the bare generic parts. */
export function corePartTokens(dir = COMPONENTS): {
	owned: Map<string, Set<string>>
	generic: Set<string>
} {
	const owned = new Map<string, Set<string>>()
	const generic = new Set<string>()
	for (const file of svelteFiles(dir)) {
		const src = readFileSync(file, 'utf8')
		for (const m of src.matchAll(/data-widget-part="([^"{}]*)"/g))
			for (const token of m[1]!.split(/\s+/).filter(Boolean)) {
				const dot = token.lastIndexOf('.')
				if (dot < 0) {
					generic.add(token)
					continue
				}
				const owner = token.slice(0, dot)
				const set = owned.get(owner) ?? new Set<string>()
				set.add(token.slice(dot + 1))
				owned.set(owner, set)
			}
	}
	return { owned, generic }
}

const sorted = (xs: Iterable<string>) => [...xs].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
const codes = (xs: Iterable<string>) =>
	sorted(xs)
		.map((x) => `\`${x}\``)
		.join(', ')

/** The generated block, markers included. */
export function renderWidgetParts(dir = COMPONENTS): string {
	const { owned, generic } = corePartTokens(dir)
	const lines = [BEGIN, '']
	for (const owner of sorted(owned.keys()))
		lines.push(`- **\`${owner}\`**: ${codes(owned.get(owner)!)}.`)
	lines.push(
		'',
		`Generic parts, which any widget may carry beside its own: ${codes(generic)}.`,
		'',
		END,
	)
	return lines.join('\n')
}

/** The guide with its block replaced by `block`. Throws when the markers are missing. */
export function withWidgetParts(guide: string, block: string): string {
	const from = guide.indexOf(BEGIN)
	const to = guide.indexOf(END)
	if (from < 0 || to < from) throw new Error(`${WIDGET_PARTS_GUIDE} has no widget-parts markers`)
	return guide.slice(0, from) + block + guide.slice(to + END.length)
}
