/**
 * Typed-handle generation (24 T7b): from a declaration artifact, emit a TS
 * module of `use()` handles whose type parameter carries the target's whole
 * option space — node → slot → field, with field types derived from the
 * declared schemas. `config(handle, …)` then autocompletes and typo-checks
 * the delta at the keyboard, before the compile-time coverage pass and long
 * before the instance's authoritative check.
 *
 * Generated, never written: the same declarations that ship become the
 * types, so they cannot drift from the documents.
 */
import type { AnnouncementDocument, SpecDocument } from '@serene-pub/sdk'
import type { TypeSurface } from './scaffold.js'

/** A settings-schema field → the TS type its value takes. */
function fieldType(decl: any): string {
	switch (decl?.type) {
		case 'integer':
		case 'number':
			return 'number'
		case 'boolean':
			return 'boolean'
		case 'string':
			return 'string'
		case 'enum': {
			const of: unknown[] =
				decl.of ?? (decl.members as any[])?.map((m) => m.key ?? m) ?? []
			return of.length ? of.map((v) => JSON.stringify(v)).join(' | ') : 'string'
		}
		case 'share':
		case 'perMember': {
			const members: string[] =
				(decl.members as any[])?.map((m) => String(m.key ?? m)) ?? []
			return members.length
				? `{ ${members.map((m) => `${JSON.stringify(m)}?: number`).join('; ')} }`
				: 'Record<string, number>'
		}
		default:
			return 'unknown'
	}
}

const ident = (id: string) => {
	// `core:spec/summarize-world` → `summarizeWorld` — the name segment.
	const name = id.split('/').at(-1)!.replace(/@.*$/, '')
	return name.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase())
}

function specOptionsType(
	doc: SpecDocument,
	typeOf: (definitionId: string, version: number) => TypeSurface | undefined,
): string {
	const nodes: string[] = []
	for (const node of doc.nodes) {
		const surface = typeOf(node.definitionId, node.definitionVersion)
		const slots = surface?.slots ?? {}
		const slotLines: string[] = []
		for (const [slotName, slot] of Object.entries(slots) as [string, any][]) {
			if (slot?.kind === 'parameters' && slot.schema) {
				const fields = Object.entries(slot.schema)
					.map(([f, d]) => `${JSON.stringify(f)}?: ${fieldType(d)}`)
					.join('; ')
				slotLines.push(`\t\t${JSON.stringify(slotName)}: { ${fields} }`)
			} else if (slot?.kind === 'prompts') {
				const fields = Object.keys(slot.fields ?? {})
					.map((f) => `${JSON.stringify(f)}?: string`)
					.join('; ')
				// A prompts slot also takes a reference to a shipped prompt row.
				slotLines.push(
					`\t\t${JSON.stringify(slotName)}: { ${fields} } | number`,
				)
			} else if (slot?.kind === 'template') {
				slotLines.push(`\t\t${JSON.stringify(slotName)}: string`)
			} else if (slot?.kind === 'sampling') {
				slotLines.push(
					`\t\t${JSON.stringify(slotName)}: number | Record<string, unknown>`,
				)
			}
		}
		if (slotLines.length)
			nodes.push(
				`\t${JSON.stringify(node.key)}: {\n${slotLines.join('\n')}\n\t}`,
			)
	}
	return `{\n${nodes.join('\n')}\n}`
}

/** The generated module: one typed handle per pipeline, one per genre id. */
export function generateTypedHandles(
	announcement: AnnouncementDocument,
	typeOf: (definitionId: string, version: number) => TypeSurface | undefined,
): string {
	const ns = announcement.identity.ns
	const lines: string[] = []
	lines.push(`/**`)
	lines.push(` * Typed handles for ${announcement.identity.title} (${ns}).`)
	lines.push(` * Generated by \`serene-pub types\` — regenerate, never edit:`)
	lines.push(` * the declarations that ship are the types.`)
	lines.push(` */`)
	lines.push(`import { use, type TypedExternalRef } from '@serene-pub/sdk'`)
	lines.push('')

	for (const doc of announcement.pipelines) {
		const name = ident(doc.id)
		const typeName = name[0]!.toUpperCase() + name.slice(1) + 'Options'
		lines.push(`export interface ${typeName} ${specOptionsType(doc, typeOf)}`)
		lines.push('')
		const major = doc.version.split('.')[0]
		lines.push(
			`export const ${name} = use(${JSON.stringify(`${doc.id}@^${major}`)}) as TypedExternalRef<${typeName}>`,
		)
		lines.push('')
	}

	if (announcement.genres.length) {
		lines.push(`export const genres = {`)
		for (const g of announcement.genres)
			lines.push(`\t${ident(g.id)}: ${JSON.stringify(g.id)},`)
		lines.push(`} as const`)
		lines.push('')
	}
	return lines.join('\n')
}
